{% set name = "metaflow" %}
{% set version = "2.16.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 99b7154af52509522d2adcb61925c155ae68bb79d3250d9f440e4b2681e07903


build:
  number: 0
  noarch: python
  entry_points:
    - metaflow=metaflow.cmd.main_cli:start
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - boto3
    - requests
    - setuptools

test:
  requires:
    - python {{ python_min }}
  imports:
    - metaflow
    - metaflow.client
    - metaflow.datastore
    - metaflow.datatools
    - metaflow.metadata_provider
    - metaflow.plugins
    - metaflow.plugins.aws
    - metaflow.plugins.aws.batch
  commands:
    - metaflow --help

about:
  home: https://metaflow.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Metaflow: More Data Science, Less Engineering'
  doc_url: https://docs.metaflow.org/
  dev_url: https://github.com/Netflix/metaflow

extra:
  recipe-maintainers:
    - saikonen
    - savingoyal
    - madhur-ob
