{% set name = "metaflow" %}
{% set version = "2.12.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9b2d3572f992cd08c5c8a893821d9d78c9a5490f17df7837a37ff5ba814fa118


build:
  number: 0
  noarch: python
  entry_points:
    - metaflow=metaflow.cmd.main_cli:start
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - boto3
    - requests
    - setuptools

test:
  imports:
    - metaflow
    - metaflow.client
    - metaflow.datastore
    - metaflow.datatools
    - metaflow.metadata
    - metaflow.plugins
    - metaflow.plugins.aws
    - metaflow.plugins.aws.batch
  commands:
    - metaflow --help

about:
  home: https://metaflow.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Metaflow: More Data Science, Less Engineering'
  doc_url: https://docs.metaflow.org/
  dev_url: https://github.com/Netflix/metaflow

extra:
  recipe-maintainers:
    - saikonen
    - savingoyal
