{% set name = "metaflow" %}
{% set version = "2.12.38" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1d63da09a8c132dd89d7635e6122c471790f956f63b537f5c4b5cd1fcb9b7030


build:
  number: 0
  noarch: python
  entry_points:
    - metaflow=metaflow.cmd.main_cli:start
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
    - setuptools
  run:
    - python >=2.7
    - boto3
    - requests
    - setuptools

test:
  imports:
    - metaflow
    - metaflow.client
    - metaflow.datastore
    - metaflow.datatools
    - metaflow.metadata_provider
    - metaflow.plugins
    - metaflow.plugins.aws
    - metaflow.plugins.aws.batch
  commands:
    - metaflow --help

about:
  home: https://metaflow.org/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: 'Metaflow: More Data Science, Less Engineering'
  doc_url: https://docs.metaflow.org/
  dev_url: https://github.com/Netflix/metaflow

extra:
  recipe-maintainers:
    - saikonen
    - savingoyal
